using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Diagnostics;

namespace Problem_2
{
    class Program
    {
        //Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

        //1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

        //By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

        public static bool CheckIfEven(int value)
        {
            var result = (value % 2 == 0) ? true : false;

            return result;
        }

        public static int Iteration()
        {
            var upperLimit = 4000000;

            var previousValue = 1;

            var currentValue = 2;

            var sumOfEvens = 0;

            while (currentValue < upperLimit)
            {
                if (CheckIfEven(currentValue))
                {
                    sumOfEvens += currentValue;
                }

                var holder = currentValue;

                currentValue = currentValue + previousValue;

                previousValue = holder;
            }

            return sumOfEvens;
        }

        static void Main(string[] args)
        {
            var watch = new Stopwatch();

            watch.Start();
            var sum = Iteration();
            watch.Stop();

            Console.WriteLine(string.Format("The sum of even values below 4,000,000 in the Fibonacci sequence is {0}", sum));
            Console.WriteLine(string.Format("The time taken was {0}", watch.Elapsed));
            Console.ReadLine();
        }
    }
}
